### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by dparnell** [gotthardp/erlang-ntlm#2]
Hi,

  this code looks great, however as there is no license file attached to it many people may not be able to use the code. Do you have any plans to make the code BSD or something like that?

Thanks

Daniel

**Comment by gotthardp** [comment]
Hello. I wonder why the licensing info was not included. The code is now MIT.

Cheers,
Petr

**Comment by dparnell** [comment]
Hi Petr,

  thanks for that :smile:

Daniel
